### ISSUE TITLE
有人需要你的幫忙

### ISSUE THREAD

**Issue by c2xusnpq6** [L-JINBIN/MT-Translation-Plugin#3]
https://forum.xda-developers.com/t/help-me-buy-mt-manager-vip-account.4182395/

**Comment by Aboodhassand** [comment]
`https://github.com/L-JINBIN/MT-Translation-Plugin/issues?q=is%3Aopen+is%3Aissue#issue-894651607`

**Comment by Aboodhassand** [comment]
> `
Duplicate of #`
